// ================= works & admin panels =================
var WK={res:{},busy:null};
function nodeSet(w){var s={};worksEdges(w).forEach(function(e){s[G.a[e]]=1;s[G.b[e]]=1});return s}
function clashes(){var ws=allWorks().filter(function(w){return worksEdges(w).length}),out=[];
  for(var i=0;i<ws.length;i++)for(var j=i+1;j<ws.length;j++){var a=ws[i],b=ws[j];if(!(a.from<=b.to&&b.from<=a.to))continue;if((a.hours==='peak'&&b.hours==='night')||(a.hours==='night'&&b.hours==='peak'))continue;
    var na=nodeSet(a),nb=nodeSet(b),touch=Object.keys(na).some(function(k){return nb[k]});var sh=a.stns.filter(function(s){return b.stns.indexOf(s)>=0});
    if(touch||sh.length)out.push({a:a,b:b,why:touch?(S.lang==='kn'?'ಒಂದೇ ಕಾರಿಡಾರ್‌ನಲ್ಲಿ ಸಂಪರ್ಕ':'physically connected on the same corridor'):(S.lang==='kn'?'ಒಂದೇ ಠಾಣೆ ವ್ಯಾಪ್ತಿ: ':'same station area: ')+sh.join(', ')})}
  return out}
function pWorks(){
  var dt=istNow().date,ws=allWorks(),h='<p class="mut sm">'+(S.lang==='kn'?'ಜಿಬಿಎ, ಬಿಎಂಆರ್‌ಸಿಎಲ್ ಇತ್ಯಾದಿ ಕಾಮಗಾರಿಗಳ ನೋಂದಣಿ. “ಉದಾಹರಣೆ” ಎಂದು ಗುರುತಿಸಿದವು ನೈಜ ವೇಳಾಪಟ್ಟಿಯಲ್ಲ; ನೈಜ ಕಾಮಗಾರಿ ಸೇರಿಸಿದರೆ ನೇರ ನಕ್ಷೆಗೆ ಅನ್ವಯವಾಗುತ್ತದೆ.':'Register of civic works (GBA, BMRCL, utilities). Rows tagged Illustrative are examples, not real schedules, and are not applied to the live map. Works you add are applied to the live map while active.')+'</p>';
  h+='<table><tr><th></th><th class="n">cap</th></tr>'+ws.map(function(w){var act=worksActive(w,dt,curT());return '<tr><td><b>'+esc(w.name)+'</b><div class="mut sm">'+esc(w.road)+' · '+esc((w.stns||[]).join(', '))+' · '+esc(w.from)+' → '+esc(w.to)+' · '+esc(w.hours)+'</div>'+(w.seed?'<span class="tag sim">'+T('illus')+'</span> ':'')+(act?'<span class="tag warn">'+(w.seed?'in schedule window':'active now · on live map')+'</span>':'')+(!w.seed&&isCmd()?' <button class="btn sec sm" data-a="wdel" data-id="'+esc(w.id)+'">'+T('remove')+'</button>':'')+'</td><td class="n">'+Math.round(w.cap*100)+'%</td></tr>'}).join('')+'</table>';
  var cs=clashes();h+='<h3>'+T('clash')+' ('+cs.length+')</h3>';if(!cs.length)h+='<p class="mut">–</p>';
  cs.forEach(function(c,i){var k=c.a.id+'+'+c.b.id,r=WK.res[k];h+='<div class="card"><b>'+esc(c.a.name)+'</b><br><b>'+esc(c.b.name)+'</b><div class="mut sm">'+esc(c.why)+'</div>'+
    '<div style="margin-top:6px"><button class="btn sm" data-a="wq" data-k="'+esc(k)+'" data-a1="'+esc(c.a.id)+'" data-b1="'+esc(c.b.id)+'"'+(WK.busy?' disabled':'')+'>'+(WK.busy===k?T('computing'):T('quant'))+'</button></div>';
    if(r)h+='<table style="margin-top:6px"><tr><td>'+esc(c.a.name.split(',')[0])+' '+(S.lang==='kn'?'ಮಾತ್ರ':'alone')+'</td><td class="n">'+Math.round(r.A)+'</td></tr><tr><td>'+esc(c.b.name.split(',')[0])+' '+(S.lang==='kn'?'ಮಾತ್ರ':'alone')+'</td><td class="n">'+Math.round(r.B)+'</td></tr><tr><td><b>'+(S.lang==='kn'?'ಒಟ್ಟಿಗೆ':'Together')+'</b></td><td class="n"><b>'+Math.round(r.AB)+'</b></td></tr></table><div class="warnbox"><b>'+T('advice')+':</b> '+adviceWorks(c,r)+'</div>';h+='</div>'});
  if(isCmd()){var si=WF.st,rs=roadsIn(si);if(WF.road==null||!rs.some(function(r){return r[0]===WF.road}))WF.road=rs.length?rs[0][0]:null;
    h+='<h3>'+T('addWorks')+'</h3><div class="frm"><label>Name</label><input type="text" id="wfn" placeholder="e.g. Metro pier work"><label>'+T('station')+'</label><select id="wfs">'+ST.slice().sort(function(a,b){return a.n<b.n?-1:1}).map(function(s){return '<option value="'+s.i+'"'+(s.i===si?' selected':'')+'>'+esc(s.n)+'</option>'}).join('')+'</select>'+
    '<label>Road</label><select id="wfr">'+rs.map(function(r){return '<option value="'+r[0]+'"'+(r[0]===WF.road?' selected':'')+'>'+esc(NAMES[r[0]])+'</option>'}).join('')+'</select><label>From</label><input type="date" id="wff" value="'+dt+'"><label>To</label><input type="date" id="wft" value="'+dt+'"><label>Hours</label><select id="wfh"><option value="all">all day</option><option value="peak">peak hours</option><option value="night">night only</option></select><label>Capacity %</label><input type="number" id="wfc" value="70" min="0" max="100"></div><button class="btn" data-a="wadd">'+T('addWorks')+'</button>'}
  return h}
var WF={st:0,road:null};
document.addEventListener('change',function(e){if(e.target.id==='wfs'){WF.st=+e.target.value;WF.road=null;renderPanel()}if(e.target.id==='wfr')WF.road=+e.target.value});
ACT.wadd=function(){var nm=$('wfn').value.trim();if(!nm||WF.road==null)return;var id='w'+Date.now().toString(36),w={name:nm.slice(0,80),road:NAMES[+$('wfr').value],stns:[ST[+$('wfs').value].n],from:$('wff').value,to:$('wft').value,hours:$('wfh').value,cap:Math.max(0,Math.min(1,(+$('wfc').value||70)/100)),kind:'Works',by:S.me.id||'local'};
  if(!w.from||!w.to||w.to<w.from)return;S.works[id]=w;dbSet('works/'+id,w);audit('works',id,nm);recompute();renderPanel()};
ACT.wdel=function(b){var id=b.dataset.id;delete S.works[id];dbDel('works/'+id);audit('works-remove',id,'');recompute();renderPanel()};
ACT.wq=function(b){var ws=allWorks(),A=ws.filter(function(w){return w.id===b.dataset.a1})[0],B=ws.filter(function(w){return w.id===b.dataset.b1})[0],k=b.dataset.k;if(!A||!B||WK.busy)return;WK.busy=k;renderPanel();
  function cm(list){var c=new Float32Array(G.ne);c.fill(1);list.forEach(function(w){worksEdges(w).forEach(function(e){c[e]=Math.min(c[e],w.cap)})});return c}
  var h=9.0;evalAsync(h,null,5).then(function(b0){return evalAsync(h,cm([A]),5).then(function(a){return evalAsync(h,cm([B]),5).then(function(bb){return evalAsync(h,cm([A,B]),5).then(function(ab){WK.res[k]={A:a.cost-b0.cost,B:bb.cost-b0.cost,AB:ab.cost-b0.cost};WK.busy=null;renderPanel()})})})})};
function adviceWorks(c,r){var first=r.A<=r.B?c.b:c.a,mv=r.A<=r.B?c.a:c.b,syn=r.AB-r.A-r.B,solo=Math.max(r.A,r.B);
  return 'Together they add '+Math.round(r.AB)+' vehicle-hours per hour at the morning peak'+(syn>5?' ('+Math.round(syn)+' more than the two alone add up to)':'')+'. Suggest moving "'+esc(mv.name)+'" to night hours or after "'+esc(first.name)+'" ends ('+esc(first.to)+'): peak delay falls to about '+Math.round(solo)+' veh-h/h.'}
// ---------- admin ----------
var AD={q:'',hits:[],role:'station'};
function pAdmin(){
  var ids=Object.keys(S.users),pend=Object.keys(S.reg).filter(function(i){return !S.users[i]});
  var h='<p class="mut sm">'+(S.dbOK?(S.lang==='kn'?'ಹಂಚಿದ ಡೇಟಾಬೇಸ್ ಸಕ್ರಿಯ — ಪಾತ್ರಗಳು ಲಿಂಕ್ ತೆರೆಯುವ ಎಲ്ಲರಿಗೂ ಅನ್ವಯ.':'Shared database active — roles apply to everyone who opens the link.'):(S.lang==='kn'?'ಸ್ಥಳೀಯ ಮೋಡ್ ಮಾತ್ರ: ಹಂಚಿದ ಡೇಟಾಬೇಸ್ ಲಭ್ಯವಿಲ್ಲ.':'Local-only mode: the shared database is not available in this view, changes are not shared.'))+'</p>';
  h+='<h3>'+T('pending')+' ('+pend.length+')</h3>'+(pend.length?pend.map(function(i){return userRow(i,true)}).join(''):'<p class="mut sm">–</p>');
  h+='<h3>'+T('users')+' ('+ids.length+')</h3>'+(ids.length?ids.map(function(i){return userRow(i,false)}).join(''):'<p class="mut sm">–</p>');
  h+='<h3>'+T('findPpl')+'</h3><input type="search" id="adq" placeholder="name…" style="width:100%"><div id="adhits"></div>';
  h+='<h3>'+T('audit')+'</h3>'+(S.audit.length?'<table>'+S.audit.slice(0,25).map(function(a){return '<tr><td class="sm mut">'+new Date(a.t).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Asia/Kolkata'})+'</td><td class="sm"><span data-uid="'+esc(a.who)+'">…</span> · '+esc(a.kind)+' · '+esc(a.txt||'')+'</td></tr>'}).join('')+'</table>':'<p class="mut sm">–</p>');
  h+='<h3>'+(S.lang==='kn'?'ಮಾಹಿತಿ ಮೂಲಗಳು':'Data sources')+'</h3><p class="sm mut">Roads, police sites, city boundary: OpenStreetMap. Station territories: nearest-station cells clipped to the boundary (approximate, not official). Crash records: BTP via OpenCity 2018–2025. Traffic state, incidents: simulated from a demand model on the real road graph. Replace the feed with BTP/ASTraM data to go live.</p>';
  return h}
function userRow(id,pending){var u=S.users[id]||{role:'station'};
  return '<div class="card"><div class="row"><b data-uid="'+esc(id)+'">…</b>'+(pending?'':'<span class="tag">'+esc(u.role)+(u.region?' · '+esc(u.region):'')+(u.station?' · '+esc(u.station):'')+'</span>')+'</div>'+
   '<div class="row" style="margin-top:6px"><select data-r="'+esc(id)+'" class="ur"><option value="viewer">Viewer</option><option value="station"'+(u.role==='station'?' selected':'')+'>Station in-charge</option><option value="dcp"'+(u.role==='dcp'?' selected':'')+'>DCP (region)</option><option value="commissioner"'+(u.role==='commissioner'?' selected':'')+'>Commissioner</option><option value="admin"'+(u.role==='admin'?' selected':'')+'>Admin</option></select>'+
   '<select data-g="'+esc(id)+'">'+REGS.map(function(r){return '<option'+(u.region===r?' selected':'')+'>'+r+'</option>'}).join('')+'</select><select data-s="'+esc(id)+'">'+ST.slice().sort(function(a,b){return a.n<b.n?-1:1}).map(function(s){return '<option'+(u.station===s.n?' selected':'')+'>'+esc(s.n)+'</option>'}).join('')+'</select>'+
   '<button class="btn sm" data-a="uset" data-id="'+esc(id)+'">'+T('assign')+'</button>'+(!pending?'<button class="btn sec sm" data-a="udel" data-id="'+esc(id)+'">'+T('remove')+'</button>':'')+'</div></div>'}
ACT.uset=function(b){var id=b.dataset.id,q=function(s){return document.querySelector('['+s+'="'+id+'"]')},role=q('data-r').value,reg=q('data-g').value,stn=q('data-s').value;
  var v={role:role,by:S.me.id||'local',at:Date.now()};if(role==='dcp')v.region=reg;if(role==='station'){v.station=stn;v.region=ST[stByName(stn)].r}S.users[id]=v;dbSet('users/'+id,v);audit('role',id,role+(v.region?' '+v.region:'')+(v.station?' '+v.station:''));renderPanel()};
ACT.udel=function(b){var id=b.dataset.id;delete S.users[id];dbDel('users/'+id);audit('role-remove',id,'');renderPanel()};
function adminAfter(){var ids=[];document.querySelectorAll('[data-uid]').forEach(function(el){ids.push(el.dataset.uid)});
  S.userCap&&S.userCap.profiles(ids).then(function(ps){document.querySelectorAll('[data-uid]').forEach(function(el){var p=ps[el.dataset.uid];el.textContent=(p&&p.name)||(el.dataset.uid===S.me.id?'You':'Someone ('+el.dataset.uid.slice(-4)+')')})}).catch(function(){});
  var q=$('adq');if(q){q.value=AD.q;q.oninput=function(){AD.q=q.value;if(!S.userCap)return;S.userCap.search(AD.q).then(function(hs){AD.hits=hs;showHits()})};showHits()}}
function showHits(){var el=$('adhits');if(!el)return;if(!S.userCap){el.innerHTML='<p class="mut sm">People search unavailable in this view.</p>';return}el.innerHTML='';AD.hits.forEach(function(p){var d=document.createElement('div');d.className='row';d.style.margin='4px 0';var s=document.createElement('span');s.textContent=p.name;var b=document.createElement('button');b.className='btn sec sm';b.textContent=T('assign');b.onclick=function(){S.reg[p.id]={t:Date.now()};renderPanel()};d.appendChild(s);d.appendChild(b);el.appendChild(d)})}
